# Generated by Django 3.1.3 on 2022-05-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='days_present',
        ),
    ]
