# Generated by Django 3.1.3 on 2022-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_days_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days_present',
            field=models.IntegerField(default=0),
        ),
    ]
